apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: finance-data-claim
spec:
  storageClassName: finance-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi