---
kind: Endpoints
apiVersion: v1
metadata:
  name: gluster-cluster
subsets:
  - addresses:
      - ip: 192.168.1.252
    ports:
      - port: 1729
  - addresses:
      - ip: 192.168.1.252
    ports:
      - port: 1729
  - addresses:
      - ip: 192.168.1.250
    ports:
      - port: 1729
